
theme: jekyll-theme-modernist
title: Swift By Hicks
author: Jakob Neufeld
email: your-email@domain.com
description: > # Hujhjkhfkjshfjksdfhsdfhjsdfhkjsdfhjkdshfjdskf
  A website with a handfull of tips and tricks with swift.
# social links
github_username:  jakobneufeld
show_excerpts: true # set to false to remove excerpts on the homepage+
